# Generated by Django 4.2.5 on 2023-10-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_picture', models.ImageField(upload_to='')),
                ('event_venue', models.CharField(max_length=100)),
                ('event_details', models.TextField()),
                ('event_price', models.PositiveIntegerField()),
                ('event_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Event',
            },
        ),
    ]
